### ISSUE TITLE
言語を日本語にするとRT数がHIDEできない

### ISSUE THREAD

**Issue by mejirot** [kawarimidoll/blueswan#5]
aria-label="リポストまたは引用"  
に変化するようです。

**Comment by kawarimidoll** [comment]
かくにんします

**Comment by kawarimidoll** [comment]
@mejirot 

修正バージョンを[v1.6.5](https://github.com/kawarimidoll/blueswan/releases/tag/1.6.5)でリリースしました。
Chrome拡張機能の審査が終わり次第、お使いのブラウザに反映されると思います。

Thank you for your reporting!
